version: "2"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: midsk
      MYSQL_DATABASE: message_data
    ports:
      - "3307:3306"
    expose:
      - 3306
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8888"
    links:
      - db